In [55]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")
pd.set_option("display.max_columns",None)

In [56]:
dataset=pd.read_csv("train_CloudCondition.csv",low_memory=False)
dataset.head()

Day Cloud_Condition Rain_OR_SNOW Temperature (C)  Apparent Temperature (C)  \
0    1   Partly Cloudy         rain             -13                     -19.0   
1    2   Partly Cloudy         rain              15                       5.0   
2    3   Partly Cloudy         rain              33                     -12.0   
3    4   Partly Cloudy         snow              30                      36.0   
4    5   Partly Cloudy         snow              27                      30.0   

   Humidity  Wind Speed (km/h)  Wind Bearing (degrees)  Visibility (km)  \
0  0.134364               17.0                    68.0              4.0   
1  0.847434                8.0                   291.0              2.0   
2  0.763775               32.0                    32.0              8.0   
3  0.255069               15.0                   130.0              3.0   
4  0.495435               63.0                    60.0             15.0   

   Pressure (millibars) Condensation  Solar irradiance intensity  
0                1008.0        Frost                        1068  
1                1036.0        Frost                        1291  
2                1004.0          Dry                        1433  
3                1016.0          Dry                        1410  
4                1007.0          Fog                        1391

In [57]:
dataset.shape

(71428, 12)

In [58]:
dataset.head()

Day Cloud_Condition Rain_OR_SNOW Temperature (C)  Apparent Temperature (C)  \
0    1   Partly Cloudy         rain             -13                     -19.0   
1    2   Partly Cloudy         rain              15                       5.0   
2    3   Partly Cloudy         rain              33                     -12.0   
3    4   Partly Cloudy         snow              30                      36.0   
4    5   Partly Cloudy         snow              27                      30.0   

   Humidity  Wind Speed (km/h)  Wind Bearing (degrees)  Visibility (km)  \
0  0.134364               17.0                    68.0              4.0   
1  0.847434                8.0                   291.0              2.0   
2  0.763775               32.0                    32.0              8.0   
3  0.255069               15.0                   130.0              3.0   
4  0.495435               63.0                    60.0             15.0   

   Pressure (millibars) Condensation  Solar irradiance intensity  
0                1008.0        Frost                        1068  
1                1036.0        Frost                        1291  
2                1004.0          Dry                        1433  
3                1016.0          Dry                        1410  
4                1007.0          Fog                        1391

In [59]:
#crearting a copy of data frame
training_data=pd.DataFrame.copy(dataset)

In [60]:
training_data=training_data.drop(["Condensation","Solar irradiance intensity"],axis=1)

In [61]:
training_data.shape

(71428, 10)

In [62]:
for i in training_data.columns:
    print({i:training_data[i].unique()})

{'Day': array([    1,     2,     3, ..., 79998, 79999, 80000], dtype=int64)}
{'Cloud_Condition': array(['Partly Cloudy', 'Light Rain', 'Breezy and Dry', 'Overcast',
       'Foggy', 'Breezy and Mostly Cloudy', 'Clear',
       'Breezy and Partly Cloudy', 'Breezy and Overcast',
       'Humid and Mostly Cloudy', 'Mostly Cloudy',
       'Humid and Partly Cloudy', 'Windy and Foggy', 'Windy and Overcast',
       'Breezy and Foggy', 'Windy and Partly Cloudy', 'Breezy',
       'Dry and Partly Cloudy', 'Windy and Mostly Cloudy',
       'Dangerously Windy and Partly Cloudy', 'Dry', 'Windy',
       'Humid and Overcast', 'Drizzle', 'Windy and Dry',
       'Dry and Mostly Cloudy'], dtype=object)}
{'Rain_OR_SNOW': array(['rain', 'snow', nan], dtype=object)}
{'Temperature (C)': array(['-13', '15', '33', '30', '27', '-17', '-5', '-14', '10', '7', '9',
       '20', '3', '29', '-8', '-15', '-20', '36', '32', '6', '17', '28',
       '-21', '23', '-4', '25', '-7', '16', '39', '-1', '13', '35', '22',
      

In [63]:
training_data["Temperature (C)"]=pd.to_numeric(training_data["Temperature (C)"], errors="coerce")

In [64]:
training_data.dtypes

Day                           int64
Cloud_Condition              object
Rain_OR_SNOW                 object
Temperature (C)             float64
Apparent Temperature (C)    float64
Humidity                    float64
Wind Speed (km/h)           float64
Wind Bearing (degrees)      float64
Visibility (km)             float64
Pressure (millibars)        float64
dtype: object

In [65]:
#checking missing values
training_data.isnull().sum()

Day                           0
Cloud_Condition               0
Rain_OR_SNOW                115
Temperature (C)             253
Apparent Temperature (C)      3
Humidity                      1
Wind Speed (km/h)             2
Wind Bearing (degrees)       37
Visibility (km)              20
Pressure (millibars)         65
dtype: int64

In [66]:
#replacing the missing value with mode values
for value in ['Rain_OR_SNOW']:
   training_data[value].fillna(training_data[value].mode()[0],inplace=True)
  

In [67]:
#imputing numerical missing data with mean value
training_data["Temperature (C)"].fillna(int(training_data["Temperature (C)"].mean()),inplace=True)
training_data["Apparent Temperature (C)"].fillna(int(training_data["Apparent Temperature (C)"].mean()),inplace=True)
training_data["Humidity"].fillna(int(training_data["Humidity"].mean()),inplace=True)
training_data["Wind Speed (km/h)"].fillna(int(training_data["Wind Speed (km/h)"].mean()),inplace=True)
training_data["Wind Bearing (degrees)"].fillna(int(training_data["Wind Bearing (degrees)"].mean()),inplace=True)
training_data["Visibility (km)"].fillna(int(training_data["Visibility (km)"].mean()),inplace=True)
training_data["Pressure (millibars)"].fillna(int(training_data["Pressure (millibars)"].mean()),inplace=True)

In [68]:
training_data.columns

Index(['Day', 'Cloud_Condition', 'Rain_OR_SNOW', 'Temperature (C)',
       'Apparent Temperature (C)', 'Humidity', 'Wind Speed (km/h)',
       'Wind Bearing (degrees)', 'Visibility (km)', 'Pressure (millibars)'],
      dtype='object')

In [69]:
training_data.describe()

Day  Temperature (C)  Apparent Temperature (C)      Humidity  \
count  71428.000000     71428.000000              71428.000000  71428.000000   
mean   37170.170451         8.959078                  5.550582      0.501013   
std    22250.741209        17.597517                 19.093422      0.289435   
min        1.000000       -21.000000                -27.000000      0.000000   
25%    18275.750000        -6.000000                -11.000000      0.249224   
50%    36132.500000         9.000000                  5.000000      0.501458   
75%    53989.250000        24.000000                 22.000000      0.751976   
max    80000.000000        39.000000                 38.000000      0.999990   

       Wind Speed (km/h)  Wind Bearing (degrees)  Visibility (km)  \
count       71428.000000            71428.000000     71428.000000   
mean           31.525816              179.221678         8.014602   
std            18.506839              103.702340         4.907206   
min             0.000000                0.000000         0.000000   
25%            16.000000               89.000000         4.000000   
50%            31.000000              180.000000         8.000000   
75%            48.000000              269.000000        12.000000   
max            63.000000              359.000000        16.000000   

       Pressure (millibars)  
count          71428.000000  
mean            1022.979714  
std               13.553689  
min             1000.000000  
25%             1011.000000  
50%             1023.000000  
75%             1035.000000  
max             1046.000000

In [70]:
training_data.isnull().sum()

Day                         0
Cloud_Condition             0
Rain_OR_SNOW                0
Temperature (C)             0
Apparent Temperature (C)    0
Humidity                    0
Wind Speed (km/h)           0
Wind Bearing (degrees)      0
Visibility (km)             0
Pressure (millibars)        0
dtype: int64

In [71]:
training_data.dtypes

Day                           int64
Cloud_Condition              object
Rain_OR_SNOW                 object
Temperature (C)             float64
Apparent Temperature (C)    float64
Humidity                    float64
Wind Speed (km/h)           float64
Wind Bearing (degrees)      float64
Visibility (km)             float64
Pressure (millibars)        float64
dtype: object

In [72]:
training_data.shape

(71428, 10)

In [73]:
training_data.Cloud_Condition.value_counts()

Mostly Cloudy                          22017
Partly Cloudy                          17613
Overcast                               13612
Clear                                   9719
Foggy                                   5900
Breezy and Dry                           656
Breezy and Mostly Cloudy                 473
Breezy and Overcast                      454
Breezy and Partly Cloudy                 350
Light Rain                               214
Dry and Partly Cloudy                     86
Windy and Partly Cloudy                   63
Breezy                                    45
Windy and Overcast                        43
Breezy and Foggy                          34
Dry                                       34
Humid and Mostly Cloudy                   32
Windy and Mostly Cloudy                   32
Humid and Partly Cloudy                   17
Dry and Mostly Cloudy                     14
Windy                                      5
Drizzle                                    5
Humid and 

In [74]:
colname=[]
for x in training_data.columns:
    if training_data[x].dtype=='object':
        colname.append(x)
colname

['Cloud_Condition', 'Rain_OR_SNOW']

In [75]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
for x in colname:
    training_data[x]=le.fit_transform(training_data[x])

In [76]:
training_data.Cloud_Condition.value_counts()

17    22017
19    17613
18    13612
6      9719
12     5900
1       656
3       473
4       454
5       350
16      214
11       86
25       63
0        45
24       43
9        34
2        34
13       32
23       32
15       17
10       14
14        5
8         5
20        5
22        3
7         1
21        1
Name: Cloud_Condition, dtype: int64

In [77]:
training_data.head()

Day  Cloud_Condition  Rain_OR_SNOW  Temperature (C)  \
0    1               19             0            -13.0   
1    2               19             0             15.0   
2    3               19             0             33.0   
3    4               19             1             30.0   
4    5               19             1             27.0   

   Apparent Temperature (C)  Humidity  Wind Speed (km/h)  \
0                     -19.0  0.134364               17.0   
1                       5.0  0.847434                8.0   
2                     -12.0  0.763775               32.0   
3                      36.0  0.255069               15.0   
4                      30.0  0.495435               63.0   

   Wind Bearing (degrees)  Visibility (km)  Pressure (millibars)  
0                    68.0              4.0                1008.0  
1                   291.0              2.0                1036.0  
2                    32.0              8.0                1004.0  
3                   130.0              3.0                1016.0  
4                    60.0             15.0                1007.0

In [78]:
training_data.dtypes

Day                           int64
Cloud_Condition               int32
Rain_OR_SNOW                  int32
Temperature (C)             float64
Apparent Temperature (C)    float64
Humidity                    float64
Wind Speed (km/h)           float64
Wind Bearing (degrees)      float64
Visibility (km)             float64
Pressure (millibars)        float64
dtype: object

In [79]:
x_train=training_data.values[:,2:]
y_train=training_data.values[:,1]

In [80]:
print(x_train)

[[   0.  -13.  -19. ...   68.    4. 1008.]
 [   0.   15.    5. ...  291.    2. 1036.]
 [   0.   33.  -12. ...   32.    8. 1004.]
 ...
 [   0.   28.  -22. ...  149.    7. 1032.]
 [   0.  -16.   -3. ...  266.   11. 1019.]
 [   0.  -15.    8. ...  154.    6. 1023.]]


In [81]:
from sklearn.preprocessing import StandardScaler
scaler =StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)

print(x_train)

[[-0.37961968 -1.24785964 -1.28582265 ... -1.07251636 -0.81810924
  -1.10522077]
 [-0.37961968  0.34328505 -0.02883644 ...  1.07788411 -1.22567602
   0.96065191]
 [-0.37961968  1.36616379 -0.91920167 ... -1.41966621 -0.00297567
  -1.40034544]
 ...
 [-0.37961968  1.08203081 -1.44294593 ... -0.29142919 -0.20675906
   0.66552724]
 [-0.37961968 -1.41833943 -0.44783184 ...  0.83680783  0.60837451
  -0.29362793]
 [-0.37961968 -1.36151283  0.12828684 ... -0.24321394 -0.41054245
   0.00149674]]


In [82]:
# Running a basic model
from sklearn.model_selection import train_test_split
#split the data into test & train
x_train,x_test,y_train,y_test=train_test_split(x_train,y_train,test_size=0.2,random_state=10)

In [83]:
#predicting using the Decision_Tree_Classifier
from sklearn.tree import DecisionTreeClassifier

model_DecisionTree=DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=10,
            max_features=None, max_leaf_nodes=10, min_samples_leaf=5,
            min_samples_split=5, min_weight_fraction_leaf=0.0,
            presort=False, random_state=200, splitter='best')


#fit the model on the data and predict the values
model_DecisionTree.fit(x_train,y_train)
Y_pred=model_DecisionTree.predict(x_test)
print(Y_pred)
#print(list(zip(Y_test,Y_pred)))

[17. 12. 17. ... 17. 12. 12.]


In [84]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(y_test,Y_pred))

acc=accuracy_score(y_test,Y_pred)
print("Accuracy of the model: ",acc)

[[   0    0    0    0    0    0    0    0    0    1    0    0    0    3
     0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0   10    0    0    0  131
     0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    2    0    0    0    1
     0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    5    0    0    0  100
     0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    9    0    0    0   67
     0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    1    0    0    0   72
     0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0  238    0    0    0 1703
     0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    5
     0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0   20
     0    0    0    0    0    0    0]
 [   0    

In [85]:
model_DecisionTree.score(x_train,y_train)

0.32566238493577404

In [86]:
#Running ExtraTreesClassifier model
#predicting using the Bagging_Classifier
from sklearn.ensemble import ExtraTreesClassifier

model=ExtraTreesClassifier(n_estimators=110,random_state=200,max_depth=5)
#fit the model on the data and predict the values
model=model.fit(x_train,y_train)

Y_pred=model.predict(x_test)


In [87]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(y_test,Y_pred))

acc=accuracy_score(y_test,Y_pred)
print("Accuracy of the model: ",acc)

[[   0    0    0    0    0    0    0    0    0    0    0    0    0    3
     1    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    6    0    0    0  131
     4    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    1
     2    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    1    0    0    0  100
     4    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    5    0    0    0   67
     4    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0   72
     1    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0   92    0    0    0 1703
   146    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    5
     0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0   20
     0    0    0    0    0    0    0]
 [   0    

In [88]:
model.score(x_train,y_train)



0.3288824332364986

# Working on Testing Data

In [89]:
test=pd.read_csv("test_CloudCondition.csv",low_memory=False)
test.head()

Day Rain_OR_SNOW  Temperature (C)  Apparent Temperature (C)  Humidity  \
0  80002         rain              1.0                       0.0  0.078150   
1  80003         rain             -3.0                      25.0  0.653251   
2  80004         rain             18.0                      17.0  0.930970   
3  80005         rain             33.0                     -12.0  0.778844   
4  80006         rain             25.0                     -19.0  0.491523   

   Wind Speed (km/h)  Wind Bearing (degrees)  Visibility (km)  \
0               17.0                     300             10.0   
1               25.0                     322              0.0   
2               37.0                     330             12.0   
3               50.0                     350              3.0   
4               62.0                     300             12.0   

   Pressure (millibars) Condensation  Solar irradiance intensity  
0                1029.0          Fog                        1399  
1                1009.0          Dry                        1468  
2                1045.0          Dry                        1152  
3                1022.0          Fog                        1003  
4                1042.0          Fog                        1228

In [90]:
test.shape

(16452, 11)

In [91]:
test.isnull().sum()

Day                           0
Rain_OR_SNOW                  0
Temperature (C)               0
Apparent Temperature (C)      0
Humidity                      0
Wind Speed (km/h)             0
Wind Bearing (degrees)        0
Visibility (km)               0
Pressure (millibars)          0
Condensation                  0
Solar irradiance intensity    0
dtype: int64

In [92]:
for i in test.columns:
    print({i:test[i].unique()})

{'Day': array([80002, 80003, 80004, ..., 96451, 96452, 96453], dtype=int64)}
{'Rain_OR_SNOW': array(['rain', 'snow'], dtype=object)}
{'Temperature (C)': array([  1.        ,  -3.        ,  18.        ,  33.        ,
        25.        ,   8.        ,  17.        ,  13.        ,
       -12.        , -14.        ,   4.        ,  -9.        ,
        26.        ,  -6.        ,  39.        , -11.        ,
        23.        ,  -7.        ,  36.        ,   5.        ,
        15.        , -21.        ,   9.        , -20.        ,
        -8.        ,   6.        ,   7.        , -17.        ,
        -2.        ,  38.        ,  11.        ,  32.        ,
        10.        ,  28.        ,  21.        ,  22.        ,
       -15.        ,  27.        ,  24.        ,   0.        ,
        14.        ,  30.        , -16.        ,  -1.        ,
       -19.        ,  37.        ,  16.        ,   3.        ,
        35.        , -13.        ,  31.        ,  12.        ,
       -10.        ,  -5.   

In [93]:
test.dtypes

Day                             int64
Rain_OR_SNOW                   object
Temperature (C)               float64
Apparent Temperature (C)      float64
Humidity                      float64
Wind Speed (km/h)             float64
Wind Bearing (degrees)          int64
Visibility (km)               float64
Pressure (millibars)          float64
Condensation                   object
Solar irradiance intensity      int64
dtype: object

In [94]:
test=test.drop(["Solar irradiance intensity","Condensation"],axis=1)

In [95]:
test.columns

Index(['Day', 'Rain_OR_SNOW', 'Temperature (C)', 'Apparent Temperature (C)',
       'Humidity', 'Wind Speed (km/h)', 'Wind Bearing (degrees)',
       'Visibility (km)', 'Pressure (millibars)'],
      dtype='object')

In [96]:
colname=[]
for x in test.columns:
    if test[x].dtype=='object':
        colname.append(x)
colname

['Rain_OR_SNOW']

In [97]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
for x in colname:
    test[x]=le.fit_transform(test[x])

In [98]:
test.head()

Day  Rain_OR_SNOW  Temperature (C)  Apparent Temperature (C)  Humidity  \
0  80002             0              1.0                       0.0  0.078150   
1  80003             0             -3.0                      25.0  0.653251   
2  80004             0             18.0                      17.0  0.930970   
3  80005             0             33.0                     -12.0  0.778844   
4  80006             0             25.0                     -19.0  0.491523   

   Wind Speed (km/h)  Wind Bearing (degrees)  Visibility (km)  \
0               17.0                     300             10.0   
1               25.0                     322              0.0   
2               37.0                     330             12.0   
3               50.0                     350              3.0   
4               62.0                     300             12.0   

   Pressure (millibars)  
0                1029.0  
1                1009.0  
2                1045.0  
3                1022.0  
4                1042.0

In [99]:
test.dtypes

Day                           int64
Rain_OR_SNOW                  int32
Temperature (C)             float64
Apparent Temperature (C)    float64
Humidity                    float64
Wind Speed (km/h)           float64
Wind Bearing (degrees)        int64
Visibility (km)             float64
Pressure (millibars)        float64
dtype: object

In [100]:
X_test_new=test.values[:,1:]

print(X_test_new)

[[ 0.00000000e+00  1.00000000e+00  0.00000000e+00 ...  3.00000000e+02
   1.00000000e+01  1.02900000e+03]
 [ 0.00000000e+00 -3.00000000e+00  2.50000000e+01 ...  3.22000000e+02
   0.00000000e+00  1.00900000e+03]
 [ 0.00000000e+00  1.80000000e+01  1.70000000e+01 ...  3.30000000e+02
   1.20000000e+01  1.04500000e+03]
 ...
 [ 0.00000000e+00  2.20388889e+01  4.40166667e+01 ...  3.00000000e+01
   1.61000000e+01  1.01566000e+03]
 [ 0.00000000e+00  2.15222222e+01  4.57722222e+01 ...  2.00000000e+01
   1.61000000e+01  1.01595000e+03]
 [ 0.00000000e+00  2.04388889e+01  4.75277778e+01 ...  3.90000000e+01
   1.55204000e+01  1.01616000e+03]]


In [101]:
#Scaling the data 
from sklearn.preprocessing import StandardScaler
X_test_new=scaler.transform(X_test_new)
print(X_test_new)


[[-0.37961968 -0.45228729 -0.29070857 ...  1.16467157  0.40459112
   0.44418374]
 [-0.37961968 -0.67959368  1.01865208 ...  1.37681871 -1.63324281
  -1.0314396 ]
 [-0.37961968  0.51376484  0.59965667 ...  1.45396312  0.8121579
   1.62468241]
 ...
 [-0.37961968  0.74328115  2.01463907 ... -1.43895232  1.64766981
  -0.54005703]
 [-0.37961968  0.71392074  2.10658528 ... -1.53538283  1.64766981
  -0.51866049]
 [-0.37961968  0.6523586   2.1985315  ... -1.35216485  1.52955696
  -0.50316645]]


In [102]:
#  #predicting using the Decision_Tree_Classifier
#predicting using the Decision_Tree_Classifier
from sklearn.tree import DecisionTreeClassifier

model_DecisionTree=DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=10,
            max_features=None, max_leaf_nodes=10, min_samples_leaf=5,
            min_samples_split=5, min_weight_fraction_leaf=0.0,
            presort=False, random_state=200, splitter='best')


#fit the model on the data and predict the values
model_DecisionTree.fit(x_train,y_train)
Y_pred=model_DecisionTree.predict(X_test_new)
print(Y_pred)
# #print(list(zip(X_test_new,Y_pred)))

[17. 17. 17. ... 17. 17. 17.]


In [103]:
#predicting using the Bagging_Classifier
from sklearn.ensemble import ExtraTreesClassifier

model=ExtraTreesClassifier(n_estimators=110,random_state=200,max_depth=5)
#fit the model on the data and predict the values
model=model.fit(x_train,y_train)

Y_pred=model.predict(X_test_new)
print(Y_pred)

[17. 17. 17. ... 17. 17. 17.]


In [104]:
model.score(x_train,y_train)

0.3288824332364986

In [105]:
test_CloudCondition = pd.read_csv('test_CloudCondition.csv',header=0,index_col=0)
predictions = test_CloudCondition
predictions["Cloud_Condition"]=Y_pred
predictions.head()

Rain_OR_SNOW  Temperature (C)  Apparent Temperature (C)  Humidity  \
Day                                                                       
80002         rain              1.0                       0.0  0.078150   
80003         rain             -3.0                      25.0  0.653251   
80004         rain             18.0                      17.0  0.930970   
80005         rain             33.0                     -12.0  0.778844   
80006         rain             25.0                     -19.0  0.491523   

       Wind Speed (km/h)  Wind Bearing (degrees)  Visibility (km)  \
Day                                                                 
80002               17.0                     300             10.0   
80003               25.0                     322              0.0   
80004               37.0                     330             12.0   
80005               50.0                     350              3.0   
80006               62.0                     300             12.0   

       Pressure (millibars) Condensation  Solar irradiance intensity  \
Day                                                                    
80002                1029.0          Fog                        1399   
80003                1009.0          Dry                        1468   
80004                1045.0          Dry                        1152   
80005                1022.0          Fog                        1003   
80006                1042.0          Fog                        1228   

       Cloud_Condition  
Day                     
80002             17.0  
80003             17.0  
80004             17.0  
80005             17.0  
80006             17.0

In [106]:
predictions["Cloud_Condition"]=predictions["Cloud_Condition"].map({25:"Windy and Partly Cloudy",24:"Windy and Overcast",23:"Windy and Mostly Cloudy",22:"Windy and Foggy",21:"Dangerously Windy and Partly Cloudy",20:"Humid and Overcast",19:"Partly Cloudy",18:"Overcast",17:"Mostly Cloudy",16:"Light Rain",15:"Humid and Partly Cloudy",14:"Windy",13:"Humid and Mostly Cloudy",12:"Foggy",11:"Dry and Partly Cloudy",10:"Dry and Mostly Cloudy",9:"Breezy and Foggy",8:"Drizzle",7:"Windy and Dry",6:"Clear",5:"Breezy and Partly Cloudy",4:"Breezy and Overcast",3:"Breezy and Mostly Cloudy",2:"Dry",1:"Breezy and Dry",0:"Breezy"})
predictions.head()

Rain_OR_SNOW  Temperature (C)  Apparent Temperature (C)  Humidity  \
Day                                                                       
80002         rain              1.0                       0.0  0.078150   
80003         rain             -3.0                      25.0  0.653251   
80004         rain             18.0                      17.0  0.930970   
80005         rain             33.0                     -12.0  0.778844   
80006         rain             25.0                     -19.0  0.491523   

       Wind Speed (km/h)  Wind Bearing (degrees)  Visibility (km)  \
Day                                                                 
80002               17.0                     300             10.0   
80003               25.0                     322              0.0   
80004               37.0                     330             12.0   
80005               50.0                     350              3.0   
80006               62.0                     300             12.0   

       Pressure (millibars) Condensation  Solar irradiance intensity  \
Day                                                                    
80002                1029.0          Fog                        1399   
80003                1009.0          Dry                        1468   
80004                1045.0          Dry                        1152   
80005                1022.0          Fog                        1003   
80006                1042.0          Fog                        1228   

      Cloud_Condition  
Day                    
80002   Mostly Cloudy  
80003   Mostly Cloudy  
80004   Mostly Cloudy  
80005   Mostly Cloudy  
80006   Mostly Cloudy

In [107]:
Cloud_Condition_pred=predictions["Cloud_Condition"]
print(Cloud_Condition_pred.head())

Day
80002    Mostly Cloudy
80003    Mostly Cloudy
80004    Mostly Cloudy
80005    Mostly Cloudy
80006    Mostly Cloudy
Name: Cloud_Condition, dtype: object


In [108]:
Cloud_Condition_pred.to_csv(r'Cloud_Condition_V12.csv',header=True)